import { Metadata } from 'next';
import React from 'react';

export const metadata: Metadata = {
  title: 'Courses',
  description: 'Generated by create next app',
}

export default function CoursesLayout({children}: React.ReactNode) {
  return (
      <div>{children}</div>
  )
}
