import './globals.css'
import { Noto_Sans_KR } from 'next/font/google'
import { Metadata } from 'next';
import style from '@/app/layout.module.css';
import { Header } from '@/components/header/header';
import { Sidebar } from '@/components/sidebar/sidebar';
import { Footer } from '@/components/footer/footer';
import cn from 'classnames';
import React from 'react';
import { LayoutProps } from '@/app/layout.props';

const inter = Noto_Sans_KR({
  weight: ['300', '400', '500', '700'],
  preload: true,
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'VK-Next-App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: LayoutProps) {
    return (
      <html lang="en">
        <body className={cn(inter.className, style.wrapper)}>
        <Header className={style.header}/>
        <Sidebar className={style.sidebar}/>
        <div className={style.body}>{children}</div>
        <Footer className={style.footer}/>
        </body>
      </html>
  )
}
